# Generated by Django 4.1 on 2022-08-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehistory',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
