# Generated by Django 4.1 on 2022-08-15 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bills',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
