# Generated by Django 4.1 on 2022-08-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_bills_created_at_bills_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
