# Generated by Django 4.1 on 2022-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0007_bills_email_bills_guid_bills_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='product_list',
            field=models.CharField(default='', max_length=100),
        ),
    ]
