# Generated by Django 4.1 on 2022-12-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0009_min_withdrawal_amount_jeton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeton',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
