# Generated by Django 4.1 on 2022-12-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0012_pnrtransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrtransactions',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
