# Generated by Django 4.1 on 2022-12-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0013_pnrtransactions_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehistory',
            name='is_pnr',
            field=models.BooleanField(default=False),
        ),
    ]
