# Generated by Django 4.0.4 on 2022-07-14 21:26

from django.db import migrations, models
import django.db.models.deletion
import personel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildsOfGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=100)),
                ('child_surname', models.CharField(max_length=100)),
                ('birthday', models.DateField(auto_now_add=True)),
                ('is_male', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_email', models.BooleanField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('game_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to=personel.models.get_profile_image_filepath)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('birthday', models.DateField()),
                ('is_male', models.BooleanField()),
                ('phone', models.CharField(max_length=100)),
                ('started_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonelsOfBranchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.branchs')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.personel')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(default='SOFT PLAY', max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.branchs')),
            ],
        ),
    ]
