# Generated by Django 4.0.4 on 2022-07-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childsofgames',
            name='price',
            field=models.FloatField(default=2016),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childsofgames',
            name='birthday',
            field=models.DateField(),
        ),
    ]
