# Generated by Django 4.0.4 on 2022-07-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0003_alter_childsofgames_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childsofgames',
            name='birthday',
            field=models.DateField(),
        ),
    ]
