# Generated by Django 4.0.4 on 2022-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0004_alter_childsofgames_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childsofgames',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
