from django.urls import path
from parent.views import get_or_create_jeton, jeton_converison
from parent.views import add_adult_to_family, add_balance, add_child_to_family, change_birthday, change_name_surname, change_password, change_phone, change_phone_verification, create_otp, delete_member_from_family, edit_member_from_family, extend_child_in_game, forgot_password, game_info, get_all_news, get_balance, get_balance_history, get_child_from_game, get_child_in_game, get_family, get_news, get_profile, login, play_game, register, verify_change_password, verify_forgot_password, verify_otp, iyiziPay, is_email_valid, add_or_edit_email, all_branchs, delete_person, denemeBills, denemeBillsDelete, get_jeton_history_for_earnings,get_jeton_history_for_conversions,get_qr_code, pnr_check, pnr_add_money, game_info_with_pnr, play_game_with_pnr

urlpatterns = [
    path("create-otp",create_otp),
    path("verify-otp",verify_otp),
    path("register",register),
    path("login",login),
    path("get-all-news",get_all_news),
    path("get-news/<int:news_id>",get_news),
    path("get-family",get_family),
    path("add-child-to-family",add_child_to_family),
    path("add-adult-to-family",add_adult_to_family),
    path("delete-member-from-family",delete_member_from_family),
    path("edit-member-from-family",edit_member_from_family),
    path("get-profile",get_profile),
    path("change-name-surname",change_name_surname),
    path("change-birthday",change_birthday),
    path("change-phone",change_phone),
    path("change-phone-verification",change_phone_verification),
    path("change-password",change_password),
    path("get-balance",get_balance),
    path("get-balance-history/<str:filter_type>",get_balance_history),
    path("add-balance",add_balance),
    path("game-info/<str:code>",game_info),
    path("play-game/<str:code>",play_game),
    path("forgot-password",forgot_password),
    path("verify-forgot-password",verify_forgot_password),
    path("verify-change-password",verify_change_password),
    path("extend-child-in-game",extend_child_in_game),
    path("get-child-from-game",get_child_from_game),
    path("get-child-in-game",get_child_in_game),
    path("iyizipay",iyiziPay),
    path("is-email-valid",is_email_valid),
    path("add-or-edit-email",add_or_edit_email),
    path("all-branchs",all_branchs),
    path("delete-person",delete_person),
    path("denemeBills",denemeBills),
    path("denemeBillsDelete",denemeBillsDelete),
    path("jeton-converison",jeton_converison),
    path("get-or-create-jeton", get_or_create_jeton),
    path("get-jeton-history-for-earnings",get_jeton_history_for_earnings),
    path("get-jeton-history-for-conversions",get_jeton_history_for_conversions),
    path("get-qr-code",get_qr_code),
    path("pnr-check",pnr_check),
    path("pnr-add-money",pnr_add_money),
    path("game-info-with-pnr/<str:code>/<str:pnr_code>",game_info_with_pnr),
    path("play-game-with-pnr/<str:code>/<str:pnr_code>",play_game_with_pnr),
    
]
