# Generated by Django 4.1 on 2022-12-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='campaign_price',
            field=models.FloatField(default=0),
        ),
    ]
